"""Reset migration

Revision ID: 2912d97f1f69
Revises: 
Create Date: 2023-08-24 20:01:09.332431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2912d97f1f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ingredients_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast_id', sa.Integer(), nullable=True),
    sa.Column('lunch_id', sa.Integer(), nullable=True),
    sa.Column('dinner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breakfast_id'], ['meals.id'], name=op.f('fk_meal_plans_breakfast_id_meals')),
    sa.ForeignKeyConstraint(['dinner_id'], ['meals.id'], name=op.f('fk_meal_plans_dinner_id_meals')),
    sa.ForeignKeyConstraint(['lunch_id'], ['meals.id'], name=op.f('fk_meal_plans_lunch_id_meals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals_ingredients',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_meals_ingredients_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meals_ingredients_meal_id_meals')),
    sa.PrimaryKeyConstraint('meal_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals_ingredients')
    op.drop_table('meal_plans')
    op.drop_table('meals')
    op.drop_table('ingredients')
    op.drop_table('users')
    # ### end Alembic commands ###
