"""Remove unique constraint on date column in MealPlan

Revision ID: 5b58f35d7e2e
Revises: dada7115fae9
Create Date: 2023-08-22 20:12:18.018395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b58f35d7e2e'
down_revision = 'dada7115fae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_constraint('meal_plans_date_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_unique_constraint('meal_plans_date_key', ['date'])

    # ### end Alembic commands ###
